"""added journal model

Revision ID: 3829372243f1
Revises: 5eaa19431ae8
Create Date: 2020-08-08 12:18:23.370231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3829372243f1'
down_revision = '5eaa19431ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_line', sa.String(length=300), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_journal')
    # ### end Alembic commands ###
